### ISSUE TITLE
Regexp-related test failures

### ISSUE THREAD

**Issue by eserte** [vrag86/perl-mailru-cloud-api#1]
On some of my smokers the test suite fails like this:
```
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/"space":{ <-- HERE .+?"used":(.+?),"total":(.+?)}/ at /home/cpansand/.cpan/build/2017112815/Mailru-Cloud-0.01-0/t/../lib/Mailru/Cloud/Auth.pm line 101.

#   Failed test 'Test upload file with rename'
#   at t/00_mailcloudauth.t line 81.
#                   '/test_upload.f'
#     doesn't match '(?^:test_upload \(\d+\))'
# Looks like you failed 1 test of 24.
t/00_mailcloudauth.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/24 subtests 
```

**Comment by eserte** [comment]
This happens also with 0.02.

**Comment by vrag86** [comment]
Please write description of error

**Comment by eserte** [comment]
Sorry, I cannot tell anything more. On CPAN Testers you can see that other people also have sent fail reports, see: http://matrix.cpantesters.org/?dist=Mailru-Cloud%200.02;reports=1

http://analysis.cpantesters.org/solved?distv=Mailru-Cloud-0.02 suggests that if the test is failing, then it's always t/00_mailcloudauth.t. But different test cases seem to fail, see [here](http://analysis.cpantesters.org/solved?distv=Mailru-Cloud-0.02#qr%3A%28Failed%20test%5Cs%2B%5CS%2B.%2A%29).

**Comment by eserte** [comment]
Currently it seems that there are no more pass reports for about two months: http://matrix.cpantesters.org/?dist=Mailru-Cloud%200.02;reports=1#sl=7,1

Test failure looks different now:
```
#   Failed test 'Test login'
#   at t/00_mailcloudauth.t line 43.
Not logined at t/00_mailcloudauth.t line 44.
# Looks like your test exited with 255 just after 5.
t/00_mailcloudauth.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/5 subtests 
```

**Comment by vrag86** [comment]
Solved
